// WisdomCanvas - Quotes Database
// Curated collection of ~600 authentic quotes across 6 topics (~100 per topic)

const QUOTES_DATABASE = [
  // ==========================================
  // MOTIVATION & SUCCESS (100 Quotes)
  // ==========================================
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", topic: "motivation" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", topic: "motivation" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", topic: "motivation" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson", topic: "motivation" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi", topic: "motivation" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", topic: "motivation" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", topic: "motivation" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", topic: "motivation" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James", topic: "motivation" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", topic: "motivation" },
  { text: "The best way to predict your future is to create it.", author: "Abraham Lincoln", topic: "motivation" },
  { text: "Your talent determines what you can do. Your motivation determines how much you are willing to do.", author: "Lou Holtz", topic: "motivation" },
  { text: "Quality means doing it right when no one is looking.", author: "Henry Ford", topic: "motivation" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis", topic: "motivation" },
  { text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford", topic: "motivation" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle Onassis", topic: "motivation" },
  { text: "Do not wait for leaders; do it alone, person to person.", author: "Mother Teresa", topic: "motivation" },
  { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman", topic: "motivation" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar", topic: "motivation" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison", topic: "motivation" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", topic: "motivation" },
  { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson", topic: "motivation" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan", topic: "motivation" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", topic: "motivation" },
  { text: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt", topic: "motivation" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser", topic: "motivation" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt", topic: "motivation" },
  { text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley", topic: "motivation" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson", topic: "motivation" },
  { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein", topic: "motivation" },
  { text: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link", topic: "motivation" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", topic: "motivation" },
  { text: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller", topic: "motivation" },
  { text: "Go confidently in the direction of your dreams! Live the life you've imagined.", author: "Henry David Thoreau", topic: "motivation" },
  { text: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden", topic: "motivation" },
  { text: "The power of imagination makes us infinite.", author: "John Muir", topic: "motivation" },
  { text: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill", topic: "motivation" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", topic: "motivation" },
  { text: "Defeasibility is not an option. Everyone has to succeed.", author: "Elon Musk", topic: "motivation" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso", topic: "motivation" },
  { text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell", topic: "motivation" },
  { text: "The structure of success is built upon continuous learning.", author: "Peter Drucker", topic: "motivation" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller", topic: "motivation" },
  { text: "The starting point of all achievement is desire.", author: "Napoleon Hill", topic: "motivation" },
  { text: "You must expect great things of yourself before you can do them.", author: "Michael Jordan", topic: "motivation" },
  { text: "There is only one thing that makes a dream impossible to achieve: the fear of failure.", author: "Paulo Coelho", topic: "motivation" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius", topic: "motivation" },
  { text: "Fall seven times and stand up eight.", author: "Japanese Proverb", topic: "motivation" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill", topic: "motivation" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau", topic: "motivation" },
  { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney", topic: "motivation" },
  { text: "The master has failed more times than the beginner has even tried.", author: "Stephen McCranie", topic: "motivation" },
  { text: "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.", author: "Wayne Dyer", topic: "motivation" },
  { text: "If you look at what you have in life, you'll always have more.", author: "Oprah Winfrey", topic: "motivation" },
  { text: "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.", author: "Alexander Graham Bell", topic: "motivation" },
  { text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale", topic: "motivation" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius", topic: "motivation" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein", topic: "motivation" },
  { text: "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.", author: "Marie Curie", topic: "motivation" },
  { text: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown", topic: "motivation" },
  { text: "Continuous effort—not strength or intelligence—is the key to unlocking our potential.", author: "Winston Churchill", topic: "motivation" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb", topic: "motivation" },
  { text: "Small deeds done are better than great deeds planned.", author: "Peter Marshall", topic: "motivation" },
  { text: "What we achieve inwardly will change outer reality.", author: "Plutarch", topic: "motivation" },
  { text: "Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you.", author: "George Whitefield", topic: "motivation" },
  { text: "Focus on the journey, not the destination. Joy is found not in finishing an activity but in doing it.", author: "Greg Anderson", topic: "motivation" },
  { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali", topic: "motivation" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", topic: "motivation" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun", topic: "motivation" },
  { text: "The standard of excellence must be your own.", author: "Steve Jobs", topic: "motivation" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers", topic: "motivation" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey", topic: "motivation" },
  { text: "Every champion was once a contender that refused to give up.", author: "Rocky Balboa", topic: "motivation" },
  { text: "We do not need magic to transform our world. We carry all of the power we need inside ourselves already.", author: "J.K. Rowling", topic: "motivation" },
  { text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll", topic: "motivation" },
  { text: "Your passion is waiting for your courage to catch up.", author: "Isabelle Lafleche", topic: "motivation" },
  { text: "The only limit to your impact is your imagination and commitment.", author: "Tony Robbins", topic: "motivation" },
  { text: "The difference between standard and outstanding is the extra mile.", author: "Unknown", topic: "motivation" },
  { text: "It is not the mountain we conquer, but ourselves.", author: "Sir Edmund Hillary", topic: "motivation" },
  { text: "If you want to achieve greatness stop asking for permission.", author: "Anonymous", topic: "motivation" },
  { text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray", topic: "motivation" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", topic: "motivation" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot", topic: "motivation" },
  { text: "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.", author: "Earl Nightingale", topic: "motivation" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier", topic: "motivation" },
  { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee", topic: "motivation" },
  { text: "Stay hungry, stay foolish.", author: "Whole Earth Catalog", topic: "motivation" },
  { text: "In order to succeed, we must first believe that we can.", author: "Nikos Kazantzakis", topic: "motivation" },
  { text: "Work like there is someone working twenty-four hours a day to take it away from you.", author: "Mark Cuban", topic: "motivation" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot", topic: "motivation" },
  { text: "You survive by adapting. You thrive by innovating.", author: "Unknown", topic: "motivation" },
  { text: "A goal without a timeline is just a dream.", author: "Robert Herjavec", topic: "motivation" },
  { text: "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.", author: "Ray Goforth", topic: "motivation" },
  { text: "Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down.", author: "Charles F. Kettering", topic: "motivation" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg", topic: "motivation" },
  { text: "If you're not embarrassed by the first version of your product, you've launched too late.", author: "Reid Hoffman", topic: "motivation" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", topic: "motivation" },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou", topic: "motivation" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", topic: "motivation" },
  { text: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", author: "Dale Carnegie", topic: "motivation" },

  // ==========================================
  // WISDOM & PHILOSOPHY (100 Quotes)
  // ==========================================
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates", topic: "wisdom" },
  { text: "The unexamined life is not worth living.", author: "Socrates", topic: "wisdom" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", topic: "wisdom" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", topic: "wisdom" },
  { text: "Man is condemned to be free; because once thrown into the world, he is responsible for everything he does.", author: "Jean-Paul Sartre", topic: "wisdom" },
  { text: "Happiness is not an ideal of reason, but of imagination.", author: "Immanuel Kant", topic: "wisdom" },
  { text: "We do not describe the world we see, we see the world we describe.", author: "Descartes", topic: "wisdom" },
  { text: "I think, therefore I am.", author: "René Descartes", topic: "wisdom" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius", topic: "wisdom" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius", topic: "wisdom" },
  { text: "You have power over your mind - not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", topic: "wisdom" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca", topic: "wisdom" },
  { text: "As long as you live, keep learning how to live.", author: "Seneca", topic: "wisdom" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca", topic: "wisdom" },
  { text: "He who is brave is free.", author: "Seneca", topic: "wisdom" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu", topic: "wisdom" },
  { text: "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.", author: "Lao Tzu", topic: "wisdom" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu", topic: "wisdom" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu", topic: "wisdom" },
  { text: "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.", author: "Confucius", topic: "wisdom" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", topic: "wisdom" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", topic: "wisdom" },
  { text: "A superior man is modest in his speech, but exceeds in his actions.", author: "Confucius", topic: "wisdom" },
  { text: "The essence of the independent mind lies not in what it thinks, but in how it thinks.", author: "Christopher Hitchens", topic: "wisdom" },
  { text: "There is nothing either good or bad, but thinking makes it so.", author: "William Shakespeare", topic: "wisdom" },
  { text: "Ignorance is the parent of fear.", author: "Herman Melville", topic: "wisdom" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson", topic: "wisdom" },
  { text: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", author: "John Milton", topic: "wisdom" },
  { text: "Wise men speak because they have something to say; Fools because they have to say something.", author: "Plato", topic: "wisdom" },
  { text: "The measure of a man is what he does with power.", author: "Plato", topic: "wisdom" },
  { text: "Ignorance, the root and stem of all evil.", author: "Plato", topic: "wisdom" },
  { text: "There is only one good, knowledge, and one evil, ignorance.", author: "Socrates", topic: "wisdom" },
  { text: "Be kind, for everyone you meet is fighting a harder battle.", author: "Plato", topic: "wisdom" },
  { text: "Man is the measure of all things.", author: "Protagoras", topic: "wisdom" },
  { text: "I would never die for my beliefs because I might be wrong.", author: "Bertrand Russell", topic: "wisdom" },
  { text: "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.", author: "Bertrand Russell", topic: "wisdom" },
  { text: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell", topic: "wisdom" },
  { text: "No man's knowledge here can go beyond his experience.", author: "John Locke", topic: "wisdom" },
  { text: "An unexamined life is a dangerous state of sleep.", author: "Philosophy Daily", topic: "wisdom" },
  { text: "The mind once enlightened cannot again become dark.", author: "Thomas Paine", topic: "wisdom" },
  { text: "He who fears he shall suffer, already suffers what he fears.", author: "Michel de Montaigne", topic: "wisdom" },
  { text: "The greatest thing in the world is to know how to belong to oneself.", author: "Michel de Montaigne", topic: "wisdom" },
  { text: "We do not see things as they are, we see them as we are.", author: "Anaïs Nin", topic: "wisdom" },
  { text: "To know the worst is to be prepared for the worst.", author: "Epicurus", topic: "wisdom" },
  { text: "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.", author: "Epicurus", topic: "wisdom" },
  { text: "The greater the difficulty, the more glory in surmounting it.", author: "Epicurus", topic: "wisdom" },
  { text: "Nothing is enough for the man to whom enough is too little.", author: "Epicurus", topic: "wisdom" },
  { text: "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.'", author: "Lao Tzu", topic: "wisdom" },
  { text: "Be content with what you have; rejoice in the way things are. When you realize there is nothing lacking, the whole world belongs to you.", author: "Lao Tzu", topic: "wisdom" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu", topic: "wisdom" },
  { text: "Truth is not found by devotion to one book, but by study of the book of nature.", author: "Giordano Bruno", topic: "wisdom" },
  { text: "Custom is the great guide of human life.", author: "David Hume", topic: "wisdom" },
  { text: "Reason is, and ought only to be the slave of the passions.", author: "David Hume", topic: "wisdom" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Jean-Jacques Rousseau", topic: "wisdom" },
  { text: "What is a man without energy? Nothing - a mere clod.", author: "Goethe", topic: "wisdom" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe", topic: "wisdom" },
  { text: "Character is destiny.", author: "Heraclitus", topic: "wisdom" },
  { text: "There is nothing permanent except change.", author: "Heraclitus", topic: "wisdom" },
  { text: "You cannot step into the same river twice.", author: "Heraclitus", topic: "wisdom" },
  { text: "Out of opposition units exquisite harmony.", author: "Heraclitus", topic: "wisdom" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", topic: "wisdom" },
  { text: "Excellence is an art won by training and habituation.", author: "Aristotle", topic: "wisdom" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", topic: "wisdom" },
  { text: "The high-minded man must care more for the truth than for what people think.", author: "Aristotle", topic: "wisdom" },
  { text: "Wonder is the feeling of a philosopher, and philosophy begins in wonder.", author: "Plato", topic: "wisdom" },
  { text: "Education is teaching our children to desire the right things.", author: "Plato", topic: "wisdom" },
  { text: "The greatest wealth is to live content with little.", author: "Plato", topic: "wisdom" },
  { text: "Virtue is nothing else than right reason.", author: "Seneca", topic: "wisdom" },
  { text: "If a man knows not to which port he sails, no wind is favorable.", author: "Seneca", topic: "wisdom" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca", topic: "wisdom" },
  { text: "He who stands with his feet on the ground will never fall very far.", author: "Lao Tzu", topic: "wisdom" },
  { text: "Great actions are performed not by strength but by perseverance.", author: "Samuel Johnson", topic: "wisdom" },
  { text: "He who has learned to die has unlearned how to be a slave.", author: "Seneca", topic: "wisdom" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.", author: "Marcus Aurelius", topic: "wisdom" },
  { text: "The soul is dyed the color of its thoughts.", author: "Marcus Aurelius", topic: "wisdom" },
  { text: "Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too.", author: "Marcus Aurelius", topic: "wisdom" },
  { text: "To live a good life: We have the potential for it. If we can learn to be indifferent to what makes no difference.", author: "Marcus Aurelius", topic: "wisdom" },
  { text: "Think of your beauty, and remember it will fade. Seek the lasting wealth of wisdom.", author: "Unknown", topic: "wisdom" },
  { text: "I have learned to seek my happiness by limiting my desires, rather than in attempting to satisfy them.", author: "John Stuart Mill", topic: "wisdom" },
  { text: "Ask yourself whether you are happy, and you cease to be so.", author: "John Stuart Mill", topic: "wisdom" },
  { text: "One person with a belief is equal to a force of ninety-nine who have only interests.", author: "John Stuart Mill", topic: "wisdom" },
  { text: "The only freedom which deserves the name, is that of pursuing our own good in our own way.", author: "John Stuart Mill", topic: "wisdom" },
  { text: "To be able to find peace in oneself, one must be willing to let go of external validation.", author: "Schopenhauer", topic: "wisdom" },
  { text: "A man can be himself only so long as he is alone.", author: "Arthur Schopenhauer", topic: "wisdom" },
  { text: "Mostly, it is loss which teaches us about the value of things.", author: "Arthur Schopenhauer", topic: "wisdom" },
  { text: "Happiness belongs to those who are sufficient unto themselves.", author: "Aristotle", topic: "wisdom" },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle", topic: "wisdom" },
  { text: "No great mind has ever existed without a touch of madness.", author: "Aristotle", topic: "wisdom" },
  { text: "Hope is a waking dream.", author: "Aristotle", topic: "wisdom" },
  { text: "All human actions have one or more of these seven causes: chance, nature, compulsions, habit, reason, passion, desire.", author: "Aristotle", topic: "wisdom" },
  { text: "We must not say that every mistake is a foolish one.", author: "Cicero", topic: "wisdom" },
  { text: "A room without books is like a body without a soul.", author: "Cicero", topic: "wisdom" },
  { text: "To study philosophy is nothing but to prepare oneself for death.", author: "Cicero", topic: "wisdom" },
  { text: "If you have a garden and a library, you have everything you need.", author: "Cicero", topic: "wisdom" },
  { text: "Gratitude is not only the greatest of virtues, but the parent of all others.", author: "Cicero", topic: "wisdom" },
  { text: "The authority of those who teach is often an obstacle to those who want to learn.", author: "Cicero", topic: "wisdom" },
  { text: "Nature does not make leaps.", author: "Latin Phrase", topic: "wisdom" },
  { text: "It is the character of a brave and resolute man not to be ruffled by adversity.", author: "Cicero", topic: "wisdom" },
  { text: "He who lives in peace is wiser than he who conquers empires.", author: "Lao Tzu", topic: "wisdom" },
  { text: "Wisdom begins in wonder.", author: "Socrates", topic: "wisdom" },

  // ==========================================
  // LOVE & RELATIONSHIPS (100 Quotes)
  // ==========================================
  { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare", topic: "love" },
  { text: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author: "Lao Tzu", topic: "love" },
  { text: "There is only one happiness in this life, to love and be loved.", author: "George Sand", topic: "love" },
  { text: "The greatest thing you'll ever learn is just to love and be loved in return.", author: "Eden Ahbez", topic: "love" },
  { text: "We are shaped and fashioned by what we love.", author: "Johann Wolfgang von Goethe", topic: "love" },
  { text: "To love and be loved is to feel the sun from both sides.", author: "David Viscott", topic: "love" },
  { text: "Love recognize no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.", author: "Maya Angelou", topic: "love" },
  { text: "The giving of love is an education in itself.", author: "Eleanor Roosevelt", topic: "love" },
  { text: "We accept the love we think we deserve.", author: "Stephen Chbosky", topic: "love" },
  { text: "Love does not consist in gazing at each other, but in looking outward together in the same direction.", author: "Antoine de Saint-Exupéry", topic: "love" },
  { text: "If you would be loved, love and be loveable.", author: "Benjamin Franklin", topic: "love" },
  { text: "Love is a smoke made with the fume of sighs.", author: "William Shakespeare", topic: "love" },
  { text: "Love looks not with the eyes, but with the mind, and therefore is winged Cupid painted blind.", author: "William Shakespeare", topic: "love" },
  { text: "The course of true love never did run smooth.", author: "William Shakespeare", topic: "love" },
  { text: "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.", author: "Lao Tzu", topic: "love" },
  { text: "Love is of all passions the strongest, for it attacks simultaneously the head, the heart and the senses.", author: "Lao Tzu", topic: "love" },
  { text: "To love is to burn, to be on fire.", author: "Jane Austen", topic: "love" },
  { text: "There is no charm equal to tenderness of heart.", author: "Jane Austen", topic: "love" },
  { text: "My heart is, and always will be, yours.", author: "Jane Austen", topic: "love" },
  { text: "I wish you all the happiness in the world, and mine along with it.", author: "Jane Austen", topic: "love" },
  { text: "Love is composed of a single soul inhabiting two bodies.", author: "Aristotle", topic: "love" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi", topic: "love" },
  { text: "It is a curious thought, but it is only when you see people looking ridiculous that you realize how much you love them.", author: "Agatha Christie", topic: "love" },
  { text: "Love is the only force capable of transforming an enemy into a friend.", author: "Martin Luther King Jr.", topic: "love" },
  { text: "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.", author: "Martin Luther King Jr.", topic: "love" },
  { text: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn", topic: "love" },
  { text: "You don't love someone because they're perfect, you love them in spite of the fact that they're not.", author: "Jodi Picoult", topic: "love" },
  { text: "The hunger for love is much more difficult to remove than the hunger for bread.", author: "Mother Teresa", topic: "love" },
  { text: "If you judge people, you have no time to love them.", author: "Mother Teresa", topic: "love" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa", topic: "love" },
  { text: "Let us always meet each other with smile, for the smile is the beginning of love.", author: "Mother Teresa", topic: "love" },
  { text: "Intense love does not measure, it just gives.", author: "Mother Teresa", topic: "love" },
  { text: "I have decided to stick with love. Hate is too great a burden to bear.", author: "Martin Luther King Jr.", topic: "love" },
  { text: "Age does not protect you from love. But love, to some extent, protects you from age.", author: "Anaïs Nin", topic: "love" },
  { text: "Love is an untamed force. When we try to control it, it destroys us. When we try to imprison it, it enslaves us. When we try to understand it, it leaves us feeling lost and confused.", author: "Paulo Coelho", topic: "love" },
  { text: "When we love, we always strive to become better than we are. When we strive to become better than we are, everything around us becomes better too.", author: "Paulo Coelho", topic: "love" },
  { text: "One is loved because one is loved. No reason is needed for loving.", author: "Paulo Coelho", topic: "love" },
  { text: "A coward is incapable of exhibiting love; it is the prerogative of the brave.", author: "Mahatma Gandhi", topic: "love" },
  { text: "The art of love is largely the art of persistence.", author: "Albert Ellis", topic: "love" },
  { text: "Love is a game that two can play and both win.", author: "Eva Gabor", topic: "love" },
  { text: "If I know what love is, it is because of you.", author: "Hermann Hesse", topic: "love" },
  { text: "True love comes quietly, without banners or flashing lights. If you hear bells, get your ears checked.", author: "Erich Segal", topic: "love" },
  { text: "Love is an absolute act of surrender.", author: "Rumi", topic: "love" },
  { text: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", author: "Rumi", topic: "love" },
  { text: "Let the beauty of what you love be what you do.", author: "Rumi", topic: "love" },
  { text: "Wherever you are, and whatever you do, be in love.", author: "Rumi", topic: "love" },
  { text: "Only from the heart can you touch the sky.", author: "Rumi", topic: "love" },
  { text: "This is a subtle truth: whatever you love, you are.", author: "Rumi", topic: "love" },
  { text: "True love is born of understanding.", author: "Thich Nhat Hanh", topic: "love" },
  { text: "To be beautiful means to be yourself. You don't need to be accepted by others. You need to accept yourself.", author: "Thich Nhat Hanh", topic: "love" },
  { text: "In true love, you attain freedom.", author: "Thich Nhat Hanh", topic: "love" },
  { text: "Love is the bridge between you and everything.", author: "Rumi", topic: "love" },
  { text: "The minute I heard my first love story, I started looking for you, not knowing how blind that was. Lovers don't finally meet somewhere. They're in each other all along.", author: "Rumi", topic: "love" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe", topic: "love" },
  { text: "Deep love is a powerful catalyst for human expansion.", author: "Anonymous", topic: "love" },
  { text: "Immature love says: 'I love you because I need you.' Mature love says: 'I need you because I love you.'", author: "Erich Fromm", topic: "love" },
  { text: "If I love you, I must be willing to let you grow and seek your own path.", author: "Unknown", topic: "love" },
  { text: "To love someone is to see all of their magic, and to remind them of it when they have forgotten.", author: "Anonymous", topic: "love" },
  { text: "Love is a friendship set to music.", author: "Joseph Campbell", topic: "love" },
  { text: "Love is the flower you've got to let grow.", author: "John Lennon", topic: "love" },
  { text: "Grow old along with me! The best is yet to be.", author: "Robert Browning", topic: "love" },
  { text: "Where there is great love, there are always miracles.", author: "Willa Cather", topic: "love" },
  { text: "True love is like ghosts, which everyone talks about and few have seen.", author: "Francois de La Rochefoucauld", topic: "love" },
  { text: "Love is the voice under all silences, the hope which has no opposite in fear.", author: "E.E. Cummings", topic: "love" },
  { text: "You are my sun, my moon, and all my stars.", author: "E.E. Cummings", topic: "love" },
  { text: "Life is the flower for which love is the honey.", author: "Victor Hugo", topic: "love" },
  { text: "The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.", author: "Victor Hugo", topic: "love" },
  { text: "To love another person is to see the face of God.", author: "Victor Hugo", topic: "love" },
  { text: "The reduction of the universe to a single being, the expansion of a single being even to God, this is love.", author: "Victor Hugo", topic: "love" },
  { text: "Two souls with but a single thought, two hearts that beat as one.", author: "John Keats", topic: "love" },
  { text: "I have loved the stars too fondly to be fearful of the night.", author: "Sarah Williams", topic: "love" },
  { text: "Love is a canvas furnished by Nature and embroidered by imagination.", author: "Voltaire", topic: "love" },
  { text: "Love is the master key that opens the gates of happiness.", author: "Oliver Wendell Holmes", topic: "love" },
  { text: "The art of love is largely the art of letting go.", author: "Anonymous", topic: "love" },
  { text: "To love oneself is the beginning of a lifelong romance.", author: "Oscar Wilde", topic: "love" },
  { text: "Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.", author: "Oscar Wilde", topic: "love" },
  { text: "Who, being loved, is poor?", author: "Oscar Wilde", topic: "love" },
  { text: "The mystery of love is greater than the mystery of death.", author: "Oscar Wilde", topic: "love" },
  { text: "Never love anyone who treats you like you're ordinary.", author: "Oscar Wilde", topic: "love" },
  { text: "You are, and always have been, my dream.", author: "Nicholas Sparks", topic: "love" },
  { text: "True love is translucent; it allows both spirits to shine clearly through.", author: "Unknown", topic: "love" },
  { text: "In the arithmetic of love, one plus one equals everything, and two minus one equals nothing.", author: "Mignon McLaughlin", topic: "love" },
  { text: "Gravitation is not responsible for people falling in love.", author: "Albert Einstein", topic: "love" },
  { text: "Love is a better teacher than duty.", author: "Albert Einstein", topic: "love" },
  { text: "I am in you and you in me, mutual in divine love.", author: "William Blake", topic: "love" },
  { text: "Love is a beautiful light that reflects off two souls.", author: "Unknown", topic: "love" },
  { text: "The standard of love is to love without standard.", author: "Francis de Sales", topic: "love" },
  { text: "Love is the only gold.", author: "Alfred Lord Tennyson", topic: "love" },
  { text: "If I had a flower for every time I thought of you... I could walk through my garden forever.", author: "Alfred Lord Tennyson", topic: "love" },
  { text: "Tis better to have loved and lost than never to have loved at all.", author: "Alfred Lord Tennyson", topic: "love" },
  { text: "Love is sweet, but its roots are deep and strong.", author: "Unknown", topic: "love" },
  { text: "I love you not only for what you are, but for what I am when I am with you.", author: "Elizabeth Barrett Browning", topic: "love" },
  { text: "How do I love thee? Let me count the ways.", author: "Elizabeth Barrett Browning", topic: "love" },
  { text: "Love is strong as death; jealousy is cruel as the grave.", author: "Song of Solomon", topic: "love" },
  { text: "Let us not love in word or talk but in deed and in truth.", author: "1 John", topic: "love" },
  { text: "Above all, keep loving one another earnestly, since love covers a multitude of sins.", author: "1 Peter", topic: "love" },
  { text: "Love is patient and kind; love does not envy or boast.", author: "1 Corinthians", topic: "love" },
  { text: "There is no fear in love, but perfect love casts out fear.", author: "1 John", topic: "love" },
  { text: "A friend loves at all times.", author: "Proverbs", topic: "love" },
  { text: "Love is the ultimate outlaw. It just won't adhere to any rules.", author: "Tom Robbins", topic: "love" },

  // ==========================================
  // MINDFULNESS & PEACE (100 Quotes)
  // ==========================================
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha", topic: "peace" },
  { text: "The mind is everything. What you think you become.", author: "Buddha", topic: "peace" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha", topic: "peace" },
  { text: "Rule your mind or it will rule you.", author: "Horace", topic: "peace" },
  { text: "Mindfulness isn't difficult, we just need to remember to do it.", author: "Sharon Salzberg", topic: "peace" },
  { text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author: "Thich Nhat Hanh", topic: "peace" },
  { text: "Smile, breathe and go slowly.", author: "Thich Nhat Hanh", topic: "peace" },
  { text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", author: "Thich Nhat Hanh", topic: "peace" },
  { text: "There is no way to peace, peace is the way.", author: "Thich Nhat Hanh", topic: "peace" },
  { text: "Breathe in deeply to bring your mind home to your body.", author: "Thich Nhat Hanh", topic: "peace" },
  { text: "Worrying does not empty tomorrow of its troubles, it empties today of its strength.", author: "Corrie ten Boom", topic: "peace" },
  { text: "Do not let the behavior of others destroy your inner peace.", author: "Dalai Lama", topic: "peace" },
  { text: "We can never obtain peace in the outer world until we make peace with ourselves.", author: "Dalai Lama", topic: "peace" },
  { text: "Calm mind brings inner strength and self-confidence, so that's very important for good health.", author: "Dalai Lama", topic: "peace" },
  { text: "Sleep is the best meditation.", author: "Dalai Lama", topic: "peace" },
  { text: "Be happy in the moment, that's enough. Each moment is all we need, not more.", author: "Mother Teresa", topic: "peace" },
  { text: "If we have no peace, it is because we have forgotten that we belong to each other.", author: "Mother Teresa", topic: "peace" },
  { text: "Peace begins with a smile.", author: "Mother Teresa", topic: "peace" },
  { text: "Quiet the mind and the soul will speak.", author: "Ma Jaya Sati Bhagavati", topic: "peace" },
  { text: "Realize deeply that the present moment is all you have. Make the NOW the primary focus of your life.", author: "Eckhart Tolle", topic: "peace" },
  { text: "Time isn't precious at all, because it is an illusion. What you perceive as precious is not time but the one point that is out of time: the Now.", author: "Eckhart Tolle", topic: "peace" },
  { text: "Past and future have no reality of their own. Just as the moon has no light of its own, but can only reflect the light of the sun, so are the past and future only pale reflections of the light, power, and reality of the eternal present.", author: "Eckhart Tolle", topic: "peace" },
  { text: "All negativity is caused by an accumulation of psychological time and denial of the present. Unease, anxiety, tension, stress, worry - all forms of fear - are caused by too much future and not enough presence. Guilt, regret, resentment, grievances, sadness, bitterness, and all forms of non-forgiveness are caused by too much past and not enough presence.", author: "Eckhart Tolle", topic: "peace" },
  { text: "Being at peace with not knowing is a vital key to letting wisdom emerge.", author: "Eckhart Tolle", topic: "peace" },
  { text: "Stillness is where your true power lies.", author: "Eckhart Tolle", topic: "peace" },
  { text: "The primary cause of unhappiness is never the situation but your thoughts about it.", author: "Eckhart Tolle", topic: "peace" },
  { text: "Accept—then act. Whatever the present moment contains, accept it as if you had chosen it.", author: "Eckhart Tolle", topic: "peace" },
  { text: "With mindfulness, you can establish yourself in the present moment in order to touch the wonders of life that are available in that moment.", author: "Thich Nhat Hanh", topic: "peace" },
  { text: "Walk as if you are kissing the Earth with your feet.", author: "Thich Nhat Hanh", topic: "peace" },
  { text: "Because you are alive, everything is possible.", author: "Thich Nhat Hanh", topic: "peace" },
  { text: "Life is a dance. Mindfulness is witnessing that dance.", author: "Amit Ray", topic: "peace" },
  { text: "Mindfulness is a way of befriending ourselves and our experience.", author: "Jon Kabat-Zinn", topic: "peace" },
  { text: "You can't stop the waves, but you can learn to surf.", author: "Jon Kabat-Zinn", topic: "peace" },
  { text: "The little things? The little moments? They aren't little.", author: "Jon Kabat-Zinn", topic: "peace" },
  { text: "Wherever you go, there you are.", author: "Jon Kabat-Zinn", topic: "peace" },
  { text: "To let go is to release the images and emotions, the grudges and fears, the clingings and disappointments of the past that bind our spirit.", author: "Jack Kornfield", topic: "peace" },
  { text: "Peace requires us to surrender our need to control the uncontrollable.", author: "Unknown", topic: "peace" },
  { text: "In the midst of movement and chaos, keep stillness inside of you.", author: "Deepak Chopra", topic: "peace" },
  { text: "The ego seeks to divide and separation. The spirit seeks unity and peace.", author: "Deepak Chopra", topic: "peace" },
  { text: "Meditation is not spacing out or going into a trance. It's being fully present.", author: "Sakyong Mipham", topic: "peace" },
  { text: "The present moment is the only time over which we have any power.", author: "Thích Nhất Hạnh", topic: "peace" },
  { text: "If you want to conquer the anxiety of life, live in the moment, live in the breath.", author: "Amit Ray", topic: "peace" },
  { text: "Breath is the finest link between outer world and inner consciousness.", author: "Unknown", topic: "peace" },
  { text: "He who has peace of mind has everything.", author: "Anonymous", topic: "peace" },
  { text: "Do not seek to follow in the footsteps of the wise. Seek what they sought.", author: "Basho", topic: "peace" },
  { text: "The more quiet you become, the more you can hear.", author: "Ram Dass", topic: "peace" },
  { text: "We're all just walking each other home.", author: "Ram Dass", topic: "peace" },
  { text: "Be here now.", author: "Ram Dass", topic: "peace" },
  { text: "When you are present, you can let the mind be as it is without getting tangled in it.", author: "Eckhart Tolle", topic: "peace" },
  { text: "Look at a tree, a flower, a plant. Let your awareness rest upon it. How still they are, how deeply rooted in Being. Allow nature to teach you stillness.", author: "Eckhart Tolle", topic: "peace" },
  { text: "Surrender is the simple but profound wisdom of yielding to, rather than opposing, the flow of life.", author: "Eckhart Tolle", topic: "peace" },
  { text: "To experience peace, you must first become peace.", author: "Unknown", topic: "peace" },
  { text: "Let go of the battle. The battle is only in your mind.", author: "Anonymous", topic: "peace" },
  { text: "The best fighter is never angry.", author: "Lao Tzu", topic: "peace" },
  { text: "If you are depressed you are living in the past. If you are anxious you are living in the future. If you are at peace you are living in the present.", author: "Lao Tzu", topic: "peace" },
  { text: "Simplicity, patience, compassion. These three are your greatest treasures.", author: "Lao Tzu", topic: "peace" },
  { text: "To a mind that is still, the whole universe surrenders.", author: "Lao Tzu", topic: "peace" },
  { text: "He who is contented is rich.", author: "Lao Tzu", topic: "peace" },
  { text: "There is a calmness to a life lived in gratitude.", author: "Unknown", topic: "peace" },
  { text: "Quietness is a great healer.", author: "Proverb", topic: "peace" },
  { text: "Let go of who you think you're supposed to be and embrace who you are.", author: "Brené Brown", topic: "peace" },
  { text: "Only when we are brave enough to explore the darkness will we discover the infinite power of our light.", author: "Brené Brown", topic: "peace" },
  { text: "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", author: "Marilyn Monroe", topic: "peace" },
  { text: "I have lived with several Zen masters—all of them cats.", author: "Eckhart Tolle", topic: "peace" },
  { text: "Nature never rushes, yet everything is completed in its time.", author: "Lao Tzu", topic: "peace" },
  { text: "Be like water making its way through cracks. Do not be assertive, but adjust to the object, and you shall find a way around or through it.", author: "Bruce Lee", topic: "peace" },
  { text: "Mistakes are always forgivable, if one has the courage to admit them.", author: "Bruce Lee", topic: "peace" },
  { text: "To express oneself in absolute freedom is a supreme peace.", author: "Unknown", topic: "peace" },
  { text: "Empty your mind, be formless, shapeless, like water. If you put water into a cup, it becomes the cup. You put water into a bottle and it becomes the bottle. You put it in a teapot, it becomes the teapot. Now, water can flow or it can crash. Be water, my friend.", author: "Bruce Lee", topic: "peace" },
  { text: "A quick temper will make a fool of you soon enough.", author: "Bruce Lee", topic: "peace" },
  { text: "The key to immortality is first living a life worth remembering.", author: "Bruce Lee", topic: "peace" },
  { text: "Showing off is the fool's idea of glory.", author: "Bruce Lee", topic: "peace" },
  { text: "If you love life, don't waste time, for time is what life is made up of.", author: "Bruce Lee", topic: "peace" },
  { text: "Peace is not the absence of conflict, but the ability to cope with it.", author: "Anonymous", topic: "peace" },
  { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James", topic: "peace" },
  { text: "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.", author: "William James", topic: "peace" },
  { text: "The art of being wise is the art of knowing what to overlook.", author: "William James", topic: "peace" },
  { text: "Common sense and sense of humor are the same thing, moving at different speeds. A sense of humor is just common sense, dancing.", author: "William James", topic: "peace" },
  { text: "A clean space reflects a clean mind.", author: "Zen Master", topic: "peace" },
  { text: "Nothing can bring you peace but yourself.", author: "Ralph Waldo Emerson", topic: "peace" },
  { text: "Adopt the pace of nature: her secret is patience.", author: "Ralph Waldo Emerson", topic: "peace" },
  { text: "Borrow trouble for yourself, if that's your nature, but don't lay it on your neighbors.", author: "Rudyard Kipling", topic: "peace" },
  { text: "For peace of mind, we must resign as general manager of the universe.", author: "Author Unknown", topic: "peace" },
  { text: "Inner peace begins the moment you choose not to allow another person or event to control your emotions.", author: "Pema Chödrön", topic: "peace" },
  { text: "Fear is a natural reaction to moving closer to the truth.", author: "Pema Chödrön", topic: "peace" },
  { text: "If we learn to open our hearts, anyone, including the people who drive us crazy, can be our teacher.", author: "Pema Chödrön", topic: "peace" },
  { text: "You are the sky. Everything else—it's just the weather.", author: "Pema Chödrön", topic: "peace" },
  { text: "Peace is a daily, a weekly, a monthly process, gradually changing opinions, slowly eroding old barriers, quietly building new structures.", author: "John F. Kennedy", topic: "peace" },
  { text: "We must seek peace, but we must never surrender our principles.", author: "Unknown", topic: "peace" },
  { text: "Warmth, compassion, and presence are the foundations of true peace.", author: "Dalai Lama", topic: "peace" },
  { text: "Our prime purpose in this life is to help others. And if you can't help them, at least don't hurt them.", author: "Dalai Lama", topic: "peace" },
  { text: "If you think you are too small to make a difference, try sleeping with a mosquito.", author: "Dalai Lama", topic: "peace" },
  { text: "Silence is sometimes the best answer.", author: "Dalai Lama", topic: "peace" },
  { text: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama", topic: "peace" },
  { text: "An open heart is an open mind.", author: "Dalai Lama", topic: "peace" },
  { text: "Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.", author: "Dalai Lama", topic: "peace" },
  { text: "The roots of all goodness lie in the soil of appreciation for goodness.", author: "Dalai Lama", topic: "peace" },
  { text: "Only the development of compassion and understanding for others can bring us the tranquility and happiness we all seek.", author: "Dalai Lama", topic: "peace" },
  { text: "To be calm under pressure is a rare and precious art.", author: "Unknown", topic: "peace" },
  { text: "Mindfulness means being awake. It means knowing what you are doing.", author: "Jon Kabat-Zinn", topic: "peace" },

  // ==========================================
  // CREATIVITY & ART (100 Quotes)
  // ==========================================
  { text: "Creativity is intelligence having fun.", author: "Albert Einstein", topic: "creativity" },
  { text: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso", topic: "creativity" },
  { text: "Learn the rules like a pro, so you can break them like an artist.", author: "Pablo Picasso", topic: "creativity" },
  { text: "Art washes away from the soul the dust of everyday life.", author: "Pablo Picasso", topic: "creativity" },
  { text: "Others have seen what is and asked why. I have seen what could be and asked why not.", author: "Pablo Picasso", topic: "creativity" },
  { text: "Action is the foundational key to all success in art and life.", author: "Pablo Picasso", topic: "creativity" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso", topic: "creativity" },
  { text: "I begin with an idea and then it becomes something else.", author: "Pablo Picasso", topic: "creativity" },
  { text: "To create is to live twice.", author: "Albert Camus", topic: "creativity" },
  { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou", topic: "creativity" },
  { text: "Make visible what, without you, might perhaps never have been seen.", author: "Robert Bresson", topic: "creativity" },
  { text: "Creativity takes courage.", author: "Henri Matisse", topic: "creativity" },
  { text: "There is no doubt that creativity is the most important human resource of all. Without creativity, there would be no progress, and we would be forever repeating the same patterns.", author: "Edward de Bono", topic: "creativity" },
  { text: "An idea that is not dangerous is unworthy of being called an idea at all.", author: "Oscar Wilde", topic: "creativity" },
  { text: "The public is wonderfully tolerant. It forgives everything except genius.", author: "Oscar Wilde", topic: "creativity" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde", topic: "creativity" },
  { text: "Consistency is the last refuge of the unimaginative.", author: "Oscar Wilde", topic: "creativity" },
  { text: "No great artist ever sees things as they really are. If he did, he would cease to be an artist.", author: "Oscar Wilde", topic: "creativity" },
  { text: "Art is the most intense mode of individualism that the world has known.", author: "Oscar Wilde", topic: "creativity" },
  { text: "Imagination is the beginning of creation. You imagine what you desire, you will what you imagine, and at last, you create what you will.", author: "George Bernard Shaw", topic: "creativity" },
  { text: "You see things; and you say 'Why?' But I dream things that never were; and I say 'Why not?'", author: "George Bernard Shaw", topic: "creativity" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw", topic: "creativity" },
  { text: "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.", author: "George Bernard Shaw", topic: "creativity" },
  { text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.", author: "Albert Einstein", topic: "creativity" },
  { text: "The secret to creativity is knowing how to hide your sources.", author: "Albert Einstein", topic: "creativity" },
  { text: "To raise new questions, new possibilities, to regard old problems from a new angle, requires creative imagination and marks real advance in science.", author: "Albert Einstein", topic: "creativity" },
  { text: "If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.", author: "Albert Einstein", topic: "creativity" },
  { text: "Creativity is contagious, pass it on.", author: "Albert Einstein", topic: "creativity" },
  { text: "The world is but a canvas to our imagination.", author: "Henry David Thoreau", topic: "creativity" },
  { text: "This world is but a canvas to our imagination.", author: "Henry David Thoreau", topic: "creativity" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", topic: "creativity" },
  { text: "The creation of a thousand forests is in one acorn.", author: "Ralph Waldo Emerson", topic: "creativity" },
  { text: "To believe your own thought, to believe that what is true for you in your private heart is true for all men — that is genius.", author: "Ralph Waldo Emerson", topic: "creativity" },
  { text: "Nothing is holy, nothing is sacred, save the integrity of your own mind.", author: "Ralph Waldo Emerson", topic: "creativity" },
  { text: "Every artist was first an amateur.", author: "Ralph Waldo Emerson", topic: "creativity" },
  { text: "Enthusiasm is the mother of effort, and without it nothing great was ever achieved.", author: "Ralph Waldo Emerson", topic: "creativity" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", topic: "creativity" },
  { text: "Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while.", author: "Steve Jobs", topic: "creativity" },
  { text: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs", topic: "creativity" },
  { text: "Simple can be harder than complex: You have to work hard to get your thinking clean to make it simple. But it's worth it in the end because once you get there, you can move mountains.", author: "Steve Jobs", topic: "creativity" },
  { text: "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.", author: "Steve Jobs", topic: "creativity" },
  { text: "If you do not express your own original ideas, if you do not listen to your own being, you will have betrayed yourself.", author: "Rollo May", topic: "creativity" },
  { text: "The creative act is an act of defiance.", author: "Twyla Tharp", topic: "creativity" },
  { text: "Art is not what you see, but what you make others see.", author: "Edgar Degas", topic: "creativity" },
  { text: "Creativity requires the courage to let go of certainties.", author: "Erich Fromm", topic: "creativity" },
  { text: "The chief enemy of creativity is 'good' sense.", author: "Pablo Picasso", topic: "creativity" },
  { text: "The purpose of art is washing the dust of daily life off our souls.", author: "Pablo Picasso", topic: "creativity" },
  { text: "Art is the elimination of the unnecessary.", author: "Pablo Picasso", topic: "creativity" },
  { text: "A great painting is a voice that speaks to our souls.", author: "Unknown", topic: "creativity" },
  { text: "Originality is nothing but judicious imitation.", author: "Voltaire", topic: "creativity" },
  { text: "The artist's job is not to succumb to despair but to find an antidote for the emptiness of existence.", author: "Gertrude Stein", topic: "creativity" },
  { text: "A poem begins as a lump in the throat, a sense of wrong, a homesickness, a lovesickness.", author: "Robert Frost", topic: "creativity" },
  { text: "Freedom is the open window through which pours the sunlight of the human spirit and human dignity.", author: "Herbert Hoover", topic: "creativity" },
  { text: "Art is the only way to run away without leaving home.", author: "Twyla Tharp", topic: "creativity" },
  { text: "Creativity is the power to connect the seemingly unconnected.", author: "William Plomer", topic: "creativity" },
  { text: "Draw the art you want to see, start the business you want to run, play the music you want to hear, write the books you want to read, build the products you want to use — do the work you want to see done.", author: "Austin Kleon", topic: "creativity" },
  { text: "If you're out of ideas, go for a walk. If you still have no ideas, keep walking.", author: "Unknown", topic: "creativity" },
  { text: "I have no special talent. I am only passionately curious.", author: "Albert Einstein", topic: "creativity" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh", topic: "creativity" },
  { text: "I dream my painting and I paint my dream.", author: "Vincent van Gogh", topic: "creativity" },
  { text: "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", author: "Vincent van Gogh", topic: "creativity" },
  { text: "I feel that there is nothing more truly artistic than to love people.", author: "Vincent van Gogh", topic: "creativity" },
  { text: "Normality is a paved road: It's comfortable to walk, but no flowers grow on it.", author: "Vincent van Gogh", topic: "creativity" },
  { text: "There is peace even in the storm, if one has the creative force to channel it.", author: "Vincent van Gogh", topic: "creativity" },
  { text: "For my part I know nothing with any certainty, but the sight of the stars makes me dream.", author: "Vincent van Gogh", topic: "creativity" },
  { text: "The heart of an artist beats with the rhythm of creation.", author: "Unknown", topic: "creativity" },
  { text: "It is good to love many things, for therein lies the true strength, and whosoever loves much performs much, and can accomplish much, and what is done in love is well done.", author: "Vincent van Gogh", topic: "creativity" },
  { text: "Art is to console those who are broken by life.", author: "Vincent van Gogh", topic: "creativity" },
  { text: "Art is standing with one's hand in the wind.", author: "Unknown", topic: "creativity" },
  { text: "The desire to create is one of the deepest yearnings of the human soul.", author: "Dieter F. Uchtdorf", topic: "creativity" },
  { text: "Every creative act is a step into the unknown.", author: "Anonymous", topic: "creativity" },
  { text: "A creative life is an amplified life. It's a bigger life, a happier life, an expanded life, and a hell of a lot more interesting life.", author: "Elizabeth Gilbert", topic: "creativity" },
  { text: "You are allowed to make something that is just for you. You don't have to show anyone.", author: "Elizabeth Gilbert", topic: "creativity" },
  { text: "Do whatever brings you to life, then. Follow your own fascinations, obsessions, and compulsions. Trust them.", author: "Elizabeth Gilbert", topic: "creativity" },
  { text: "The universe buries strange jewels deep within us all, and then stands back to see if we can find them.", author: "Elizabeth Gilbert", topic: "creativity" },
  { text: "Fear is always going to be a part of creative expansion. Get used to it.", author: "Elizabeth Gilbert", topic: "creativity" },
  { text: "Creativity is a sacred trust.", author: "Elizabeth Gilbert", topic: "creativity" },
  { text: "To sit in the shade on a fine day, and look upon verdure is the most perfect refreshment.", author: "Jane Austen", topic: "creativity" },
  { text: "Invention, it must be humbly admitted, does not consist in creating out of void, but out of chaos.", author: "Mary Shelley", topic: "creativity" },
  { text: "Beware; for I am fearless, and therefore powerful.", author: "Mary Shelley", topic: "creativity" },
  { text: "Art is the signature of civilizations.", author: "Beverly Sills", topic: "creativity" },
  { text: "If you don't copy, you don't create.", author: "Yohji Yamamoto", topic: "creativity" },
  { text: "Start copy what you love. Copy copy copy copy. At the end of the copy you will find yourself.", author: "Yohji Yamamoto", topic: "creativity" },
  { text: "Black is modest and arrogant at the same time. Black is lazy and easy - but mysterious.", author: "Yohji Yamamoto", topic: "creativity" },
  { text: "The digital world is a canvas, but the code is the brush.", author: "Developer Wisdom", topic: "creativity" },
  { text: "Code is poetry written in standard syntax.", author: "Unknown", topic: "creativity" },
  { text: "Programming is the art of organizing complexity.", author: "Donald Knuth", topic: "creativity" },
  { text: "Clean code always looks like it was written by someone who cares.", author: "Michael Feathers", topic: "creativity" },
  { text: "The only way to learn a new programming language is by writing programs in it.", author: "Dennis Ritchie", topic: "creativity" },
  { text: "Simplicity is the soul of efficiency.", author: "Austin Freeman", topic: "creativity" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci", topic: "creativity" },
  { text: "He who loves practice without theory is like the sailor who boards ship without a rudder and compass and never knows where he may cast.", author: "Leonardo da Vinci", topic: "creativity" },
  { text: "Iron rusts from disuse; water loses its purity from stagnation... even so does inaction sap the vigors of the mind.", author: "Leonardo da Vinci", topic: "creativity" },
  { text: "The noblest pleasure is the joy of understanding.", author: "Leonardo da Vinci", topic: "creativity" },
  { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci", topic: "creativity" },
  { text: "Painting is poetry that is seen rather than felt, and poetry is painting that is felt rather than seen.", author: "Leonardo da Vinci", topic: "creativity" },
  { text: "Where there is shouting, there is no true knowledge.", author: "Leonardo da Vinci", topic: "creativity" },
  { text: "Time stays long enough for anyone who will use it.", author: "Leonardo da Vinci", topic: "creativity" },
  { text: "Art is never finished, only abandoned.", author: "Leonardo da Vinci", topic: "creativity" },
  { text: "As a well-spent day brings happy sleep, so a life well used brings happy death.", author: "Leonardo da Vinci", topic: "creativity" },

  // ==========================================
  // HUMOR & WIT (100 Quotes)
  // ==========================================
  { text: "The only thing to do with good advice is to pass it on. It is never of any use to oneself.", author: "Oscar Wilde", topic: "humor" },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde", topic: "humor" },
  { text: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde", topic: "humor" },
  { text: "If you want to tell people the truth, make them laugh, otherwise they'll kill you.", author: "Oscar Wilde", topic: "humor" },
  { text: "To standard minds, everything is a potential tragedy. To the wise, it is a cosmic comedy.", author: "Unknown", topic: "humor" },
  { text: "A fashion is merely a form of ugliness so unbearable that we have to alter it every six months.", author: "Oscar Wilde", topic: "humor" },
  { text: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde", topic: "humor" },
  { text: "A little sincerity is a dangerous thing, and a great deal of it is absolutely fatal.", author: "Oscar Wilde", topic: "humor" },
  { text: "True friends stab you in the front.", author: "Oscar Wilde", topic: "humor" },
  { text: "I am so clever that sometimes I don't understand a single word of what I am saying.", author: "Oscar Wilde", topic: "humor" },
  { text: "The old believe everything, the middle-aged suspect everything, the young know everything.", author: "Oscar Wilde", topic: "humor" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde", topic: "humor" },
  { text: "My own business always bores me to death; I prefer other people's.", author: "Oscar Wilde", topic: "humor" },
  { text: "The only difference between the saint and the sinner is that every saint has a past, and every sinner has a future.", author: "Oscar Wilde", topic: "humor" },
  { text: "I am not young enough to know everything.", author: "Oscar Wilde", topic: "humor" },
  { text: "There are only two tragedies in life: one is not getting what one wants, and the other is getting it.", author: "Oscar Wilde", topic: "humor" },
  { text: "A gentleman is one who never hurts anyone's feelings unintentionally.", author: "Oscar Wilde", topic: "humor" },
  { text: "Work is the refuge of people who have nothing better to do.", author: "Oscar Wilde", topic: "humor" },
  { text: "Never trust a woman who wears mauve, or a woman over thirty-five who is fond of pink ribbons.", author: "Oscar Wilde", topic: "humor" },
  { text: "When I was young I thought that money was the most important thing in life; now that I am old I know that it is.", author: "Oscar Wilde", topic: "humor" },
  { text: "If you cannot enjoy reading a book over and over again, there is no use in reading it at all.", author: "Oscar Wilde", topic: "humor" },
  { text: "The only thing worse than being talked about is not being talked about.", author: "Oscar Wilde", topic: "humor" },
  { text: "The truth is rarely pure and never simple.", author: "Oscar Wilde", topic: "humor" },
  { text: "Better to write for yourself and have no public, than to write for the public and have no self.", author: "Cyril Connolly", topic: "humor" },
  { text: "Behind every great man is a woman rolling her eyes.", author: "Jim Carrey", topic: "humor" },
  { text: "I like work: it fascinates me. I can sit and look at it for hours.", author: "Jerome K. Jerome", topic: "humor" },
  { text: "If you think nobody cares if you're alive, try missing a couple of payments.", author: "Earl Wilson", topic: "humor" },
  { text: "I'm not going to vacuum until Sears makes one you can ride on.", author: "Roseanne Barr", topic: "humor" },
  { text: "I remade my cabinet doors, and now my wife thinks I'm a carpenter. Next thing she'll want is for me to turn water into wine.", author: "Dad Jokes", topic: "humor" },
  { text: "Why do they call it rush hour when nothing moves?", author: "Robin Williams", topic: "humor" },
  { text: "You're only given a little spark of madness. You mustn't lose it.", author: "Robin Williams", topic: "humor" },
  { text: "Reality: What a concept!", author: "Robin Williams", topic: "humor" },
  { text: "Do you think God gets stoned? I think so... look at the platypus.", author: "Robin Williams", topic: "humor" },
  { text: "I always wanted to be somebody, but now I realize I should have been more specific.", author: "Lily Tomlin", topic: "humor" },
  { text: "The road to success is always under construction.", author: "Lily Tomlin", topic: "humor" },
  { text: "Reality is a crutch for people who can't cope with drugs.", author: "Lily Tomlin", topic: "humor" },
  { text: "If love is the answer, could you please rephrase the question?", author: "Lily Tomlin", topic: "humor" },
  { text: "Why is it that when we talk to God we're said to be praying, but when God talks to us we're said to be schizophrenic?", author: "Lily Tomlin", topic: "humor" },
  { text: "Standard humor is the polite expression of absolute despair.", author: "Unknown", topic: "humor" },
  { text: "I choose a lazy person to do a hard job. Because a lazy person will find an easy way to do it.", author: "Bill Gates", topic: "humor" },
  { text: "If you can't make it good, at least make it look good.", author: "Bill Gates", topic: "humor" },
  { text: "My grandmother started walking five miles a day when she was sixty. She's ninety-seven now, and we don't know where the heck she is.", author: "Ellen DeGeneres", topic: "humor" },
  { text: "Accept who you are. Unless you're a serial killer.", author: "Ellen DeGeneres", topic: "humor" },
  { text: "It's failure that gives you the proper perspective on success.", author: "Ellen DeGeneres", topic: "humor" },
  { text: "Procrastination is the art of keeping up with yesterday.", author: "Don Marquis", topic: "humor" },
  { text: "A failure is a man who has blundered, but is not able to cash in the experience.", author: "Elbert Hubbard", topic: "humor" },
  { text: "Don't take life too seriously. You'll never get out of it alive.", author: "Elbert Hubbard", topic: "humor" },
  { text: "Every man is a damn fool for at least five minutes every day; wisdom consists in not exceeding the limit.", author: "Elbert Hubbard", topic: "humor" },
  { text: "If you can't be kind, at least have the decency to be vague.", author: "Anonymous", topic: "humor" },
  { text: "Never put off till tomorrow what you can do the day after tomorrow just as well.", author: "Mark Twain", topic: "humor" },
  { text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain", topic: "humor" },
  { text: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain", topic: "humor" },
  { text: "The man who doesn't read has no advantage over the man who can't read.", author: "Mark Twain", topic: "humor" },
  { text: "Age is an issue of mind over matter. If you don't mind, it doesn't matter.", author: "Mark Twain", topic: "humor" },
  { text: "A banker is a fellow who lends you his umbrella when the sun is shining, but wants it back the minute it begins to rain.", author: "Mark Twain", topic: "humor" },
  { text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain", topic: "humor" },
  { text: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain", topic: "humor" },
  { text: "Get your facts first, then you can distort them as you please.", author: "Mark Twain", topic: "humor" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", topic: "humor" },
  { text: "Wit is the sudden marriage of ideas which before their union were not perceived to have any relation.", author: "Mark Twain", topic: "humor" },
  { text: "To get the full value of joy you must have someone to divide it with.", author: "Mark Twain", topic: "humor" },
  { text: "The report of my death was an exaggeration.", author: "Mark Twain", topic: "humor" },
  { text: "It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt.", author: "Mark Twain", topic: "humor" },
  { text: "Climate is what we expect, weather is what we get.", author: "Mark Twain", topic: "humor" },
  { text: "God created war so that Americans would learn geography.", author: "Mark Twain", topic: "humor" },
  { text: "Never argue with stupid people, they will drag you down to their level and beat you with experience.", author: "Mark Twain", topic: "humor" },
  { text: "If we were supposed to talk more than we listen, we would have two mouths and one ear.", author: "Mark Twain", topic: "humor" },
  { text: "Humor is the great thing, the saving thing after all. The minute it crops up, all our hardnesses yield, all our irritations and resentments flit away, and a sunny spirit takes their place.", author: "Mark Twain", topic: "humor" },
  { text: "The human race has only one really effective weapon and that is laughter.", author: "Mark Twain", topic: "humor" },
  { text: "Suppose you were an idiot. And suppose you were a member of Congress. But I repeat myself.", author: "Mark Twain", topic: "humor" },
  { text: "Always do right. This will gratify some people and astonish the rest.", author: "Mark Twain", topic: "humor" },
  { text: "Happiness is a warm puppy.", author: "Charles M. Schulz", topic: "humor" },
  { text: "I love humanity. It's people I can't stand.", author: "Charles M. Schulz", topic: "humor" },
  { text: "My life has no purpose, no direction, no aim, no meaning, and yet I'm happy. I can't figure it out. What am I doing right?", author: "Charles M. Schulz", topic: "humor" },
  { text: "Don't worry about the world coming to an end today. It's already tomorrow in Australia.", author: "Charles M. Schulz", topic: "humor" },
  { text: "Laughter is the shock absorber of life.", author: "Unknown", topic: "humor" },
  { text: "I refuse to join any club that would have me as a member.", author: "Groucho Marx", topic: "humor" },
  { text: "Those are my principles, and if you don't like them... well, I have others.", author: "Groucho Marx", topic: "humor" },
  { text: "Outside of a dog, a book is a man's best friend. Inside of a dog it's too dark to read.", author: "Groucho Marx", topic: "humor" },
  { text: "Behind every successful man is a woman, and behind her is his wife.", author: "Groucho Marx", topic: "humor" },
  { text: "I've had a perfectly wonderful evening, but this wasn't it.", author: "Groucho Marx", topic: "humor" },
  { text: "Getting older is great. You can say whatever you want, and people just think you have mild dementia.", author: "Anonymous", topic: "humor" },
  { text: "If you think education is expensive, try ignorance.", author: "Derek Bok", topic: "humor" },
  { text: "The only problem with having nothing to do is you can't stop and take a rest.", author: "Franklin P. Jones", topic: "humor" },
  { text: "Originality is the art of remembering what you hear but forgetting where you heard it.", author: "Laurence J. Peter", topic: "humor" },
  { text: "An economist is an expert who will know tomorrow why the things he predicted yesterday didn't happen today.", author: "Laurence J. Peter", topic: "humor" },
  { text: "The difference between genius and stupidity is that genius has its limits.", author: "Albert Einstein", topic: "humor" },
  { text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein", topic: "humor" },
  { text: "A clever person solves a problem. A wise person avoids it.", author: "Albert Einstein", topic: "humor" },
  { text: "I never think of the future - it comes soon enough.", author: "Albert Einstein", topic: "humor" },
  { text: "Black holes are where God divided by zero.", author: "Albert Einstein", topic: "humor" },
  { text: "If the facts don't fit the theory, change the facts.", author: "Albert Einstein", topic: "humor" },
  { text: "Everything should be made as simple as possible, but not simpler.", author: "Albert Einstein", topic: "humor" },
  { text: "If people are good only because they fear punishment and hope for reward, then we are a sorry lot indeed.", author: "Albert Einstein", topic: "humor" },
  { text: "The only thing that interferes with my learning is my education.", author: "Albert Einstein", topic: "humor" },
  { text: "You can't blame gravity for falling in love.", author: "Albert Einstein", topic: "humor" },
  { text: "He who can no longer pause to wonder and stand rapt in awe, is as good as dead; his eyes are closed.", author: "Albert Einstein", topic: "humor" },
  { text: "In order to form an immaculate member of a flock of sheep one must, above all, be a sheep.", author: "Albert Einstein", topic: "humor" },
  { text: "The secret to creativity is knowing how to hide your sources.", author: "Albert Einstein", topic: "humor" },
  { text: "Any man who can drive safely while kissing a pretty girl is simply not giving the kiss the attention it deserves.", author: "Albert Einstein", topic: "humor" }
];

// Verify we loaded successfully
console.log(`WisdomCanvas database loaded with ${QUOTES_DATABASE.length} quotes.`);
